version: "3.8"

services:
  r:
    build:
      context: ./.devcontainer/r
      dockerfile: r.Dockerfile
    container_name: m7560-r-dev
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    environment:
      - R_LIBS_USER=/workspaces/.r/library
      - RENV_PATHS_CACHE=/workspaces/.r/cache

  python:
    build:
      context: ./.devcontainer/python
      dockerfile: python.Dockerfile
    container_name: m7560-python-dev
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    environment:
      - PYTHONPATH=/workspaces/src/python
      - JUPYTER_PATH=/workspaces/notebooks

  clojure:
    build:
      context: ./.devcontainer/clojure
      dockerfile: clojure.Dockerfile
    container_name: m7560-clojure-dev
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    environment:
      - CLOJURE_DEPS=/workspaces/${localWorkspaceFolderBasename}/deps.edn

  latex:
    build:
      context: ./.devcontainer/latex
      dockerfile: latex.Dockerfile
    container_name: m7560-latex-dev
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    environment:
      - TEXMFHOME=/workspaces/.texmf