---
title: 'Final project - Math 7550 - Statistical Learning I (Fall 2024)'
name: 'Emma Naiyue Liang, Ryan Renken, Jaryt Salvo, & Jason Turk'
output:
  pdf_document: default
  html_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,warning = F,message = F)
```

##### __Instructions:__ (Please read them carefully!)

(1) You will work on the final project in groups of 3-4 students. Every member is anticipated to make a substantial contribution to the project. If a member contributes little to nothing, the other group members are required to inform the instructor. Please form your groups through Canvas by __5pm Friday, Nov 22nd__. 

(2) You may use all the given predictors or a subset of them. You may perform any needed data pre-processing steps such as centering and scaling. It is also fine to transform the predictors and/or a response variable or introduce new predictors obtained from the original ones. However, no other sources of data can be used along with the provided data set. `lubridate` is a good R package for parsing dates and times and extracting useful information from them (e.g., day of week). 

(3) You should fit at least __five__ different models to the training data and pick the one that you believe is the best. You may try the models we covered in class or their modifications/extensions which are available through the `caret` package (but not covered in class). You may also use the `Poisson regression` covered in the ISLR book on pages 167-170 and 185-189. You may also build your own custom models. If a model that you fit has tuning parameters, tune them using cross validation. Once you identify your best model, explain why you selected it and then use it to compute your predictions on the provided test set. Note that the test set _does not contain a response variable_. Since the response variable is absent in the test set, you won't be able to compute the test RMSE. Instead, you will submit your predictions stored in a csv file to me (by __5pm Wednesday, Dec 4th__) and I'll compute the test RMSE for your group. 

(3) Each group is required to give a 10-12 minute presentation of their project findings on __Thursday, Dec 5th__, 2:30PM - 3:45PM in the usual classroom. Each group member must present something of the project. 

(4) The slides and a knitted html document of your project report are both to be submitted to Canvas by __11:59pm on Friday, Dec 6th__. Include any relevant outputs such as EDA (exploratory data analysis) figures, R outputs, tables and plots in your slides and project report. Please avoid including large outputs of data that take up a lot of space. For the project report, add comments and explanations (whenever possible) for your results and findings in **bold**.

#### __Predicting visit length and occupancy at BGSU Learning Commons__

On this project you will analyze data on student visits to the BGSU Learning Commons (LC) center. The training and test sets are stored in `LC_train.csv` and `LC_test.csv`. Each row represents a visit by a BGSU student to the LC. The training and test sets contain data from the Fall 2016 - Spring 2017 and Fall 2017 - Spring 2018 academic years respectively. The data sets are de-identified with the demographics information removed. The student ID numbers are not the real BGSU ID numbers. 

_Note_: When you examine the data set, you'll observe that the vast majority of visits are attributed to senior students, which is likely due to a data entry error. The data was collected during the Fall 2020–Spring 2021 academic year, and most probably the students' class standings were recorded based on that time period. If desired, you can retrospectively adjust the recorded class standings to correct this issue.

(a) Build models to predict `Duration_In_Min` (response variable) using the other predictors except `Check_Out_Time` (the test set doesn't contain it). Make sure the predictions of your best model are in the original units (minutes). Please name your submission file as `your_group_name_duration.csv` (with all the predicted values recorded under one column).

(b) For each visit in the training set, compute `Occupancy` which is equal to the number of students present in the LC at the check-in moment of  that visit (as a test, you should get 5, 3, 3, 16, 12 and 17 as the values of `Occupancy` for the first six visits in the training set). Build models to predict `Occupancy` (response variable) using the other predictors except `Duration_In_Min` and `Check_Out_Time` (the test set doesn't contain them). Make sure the predictions of your best model are integer-valued. Please name your submission file as `your_group_name_occupancy.csv` (with all the predicted values recorded under one column).

